# Generated by Django 6.0.3 on 2026-05-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
