# Generated by Django 6.0.3 on 2026-05-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
